version: 2

jobs:
  build:
    docker:
      - image: circleci/node:9.6.1
    steps:
        - checkout
        - run:
            name: install dependencies
            command: yarn
        - run:
            name: compile
            command: npm run build
        - run:
            name: testrpc
            command: yarn chain
            background: true
        - run: yarn contracts:migrate
        - run: yarn migrations:loans
        - run: yarn jest --maxWorkers 2
  deploy_staging:
      docker:
        - image: circleci/node:9.6.1
      steps:
        - checkout
        - run:
            name: install dependencies
            command: yarn
        - run:
            name: compile
            command: npm run build
        - run:
            name: install aws cli
            command: sudo apt-get update && sudo apt-get install -y awscli
        - run: yarn deploy:staging
  deploy_production:
      docker:
        - image: circleci/node:9.6.1
      steps:
        - checkout
        - run:
            name: install dependencies
            command: yarn
        - run:
            name: compile
            command: npm run build
        - run:
            name: install aws cli
            command: sudo apt-get update && sudo apt-get install -y awscli
        - run: yarn deploy

workflows:
  version: 2
  dharma_build_process:
    jobs:
      - build
      - deploy_staging:
          requires:
              - build
          filters:
              branches:
                  only: staging
      - deploy_production:
          requires:
              - build
          filters:
              branches:
                  only: master
