version: 2

jobs:
  build:
    docker:
      - image: circleci/node:9.6.1
    steps:
        - checkout
        - run:
            name: install dependencies
            command: yarn
        - run:
            name: testrpc
            command: yarn chain
            background: true
  test:
      docker:
        - image: circleci/node:9.6.1
      steps:
        - checkout
        - run: yarn contracts:migrate
        - run: yarn migrations:loans
        - run: yarn jest --maxWorkers 2

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
