version: 2

jobs:
  build_and_test_client:
    docker:
      - image: circleci/node:9.11.1
    steps:
        - checkout
        - run:
            name: install client dependencies
            command: cd ./client && yarn
        - run:
            name: compile client
            command: cd ./client && yarn build
        - run:
            name: run testrpc
            command: yarn chain
            background: true
        - run: cd ./client && yarn contracts:migrate
        - run: cd ./client && yarn migrations:loans
        - run: yarn test

workflows:
  version: 2
  plex_build_process:
    jobs:
      - build_and_test_client
