version: 2

jobs:
  build:
    docker:
      - image: circleci/node:9.6.1
    steps:
        - checkout
        - run:
            name: install dependencies
            command: yarn
        - run:
            name: compile
            command: npm run build
        - run:
            name: testrpc
            command: yarn chain
            background: true
        - run: yarn contracts:migrate
        - run: yarn migrations:loans
        - run: yarn jest --maxWorkers 2
  deploy:
      docker:
        - image: circleci/node:9.6.1
      steps:
        - checkout
        - run:
            name: install dependencies
            command: yarn
        - run:
            name: compile
            command: npm run build
        - run: yarn deploy

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
              - build
          filters:
              branches:
                  only: master
